package no.novari.gateway.instance.config

import no.novari.gateway.instance.config.properties.InstanceProcessingEventsConfigurationProperties
import org.springframework.boot.autoconfigure.AutoConfiguration
import org.springframework.boot.context.properties.EnableConfigurationProperties

@EnableConfigurationProperties(InstanceProcessingEventsConfigurationProperties::class)
@AutoConfiguration
class KafkaConfiguration
